#include "./skyfs.h"

/*
 *  WHAT IS SKYFS?
 *
 *  A FILESYSTEM FORMATE DESIGNED SPECIFICALLY FOR THE SKYBOX OPERATING SYSTEM. THE
 *  SKYFS IS LATER USED TO RUN SKYEF FILES... I PLAN ON LATER USING SKYEF TO CREATE
 *  SUBSYSTEMS ALLOWING US TO RUN PROGRAMS FOR UNIX-LIKE OPERATING SYSTEMS, AND
 *  SUBSYSTEMS FOR OTHER PURPOSES...
 */